### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_voice#1]
If I have a set shout and the other person has a whisper set, the other person can not hear me.

**Comment by HumanTree92** [comment]
Yeah i plus 1 this all the way. If 1 person is on Shout if the other person isn't in shout he can't hear you. They both have to be in the same voice proximity. This needs to be fixed.

**Comment by HumanTree92** [comment]
This needs to be setup to where i 1 person is on Shout & someone is on Whisper they should be able to hear the person who is on Shout.

**Comment by TheRealDadbeard** [comment]
same here, it's really buggy sadly

**Comment by Krizfrost** [comment]
Figured out this is simply just a listening script it only works for your hearing not your voice distance its just your hearing distance

**Comment by DonTosti** [comment]
But it should be possible to fix right? If one person is on shoud, that the other persons can hear that even they are in whispering.

**Comment by frayCORE** [comment]
The native that is used is NetworkSetTalkerProximity. If I am not mistaken it works in an odd manner and you have to look at several scenarios to understand a bit.

If you are set to Shout, then you "might" be able to hear people in the shout range and your voice will travel up to the shout range.

However, the other individuals must have their listener/talker proximity overlap with you as well. So if Person B is within my shout range, but they are on whisper and their whisper range does not overlap with my character, then they will not hear me and I will not hear them.

The reason for this is b/c they are not only setting the range of their voice, but they are setting the range at which they can hear stuff.

So if you imagine circles around everyone, you can only hear and talk with people which both your circle and their circle overlap and cover both your characters.

This is why no matter how far you set the shout range, it does not matter if that person is on whisper, b/c they can only hear voices that have an origin within the whisper range of their hearing.
