### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by twistedcinema** [ESX-Org/esx_voice#11]
I have the script in by default. However people in game can not hear eachother?

**Comment by EGUltraTM** [comment]
Look in the GTA V settings if voice is enabled. Standard in Fivem its disabled.
And set it to push to talk and then you can talk with N

**Comment by twistedcinema** [comment]
I have everything turned on in my gtaV and FiveM settings.  I tried a different voice chat script which worked but this one does not. You can talk but players can not hear each other.

**Comment by twistedcinema** [comment]
I have recently moved hosts and no voice scripts are working whatsoever. No body can talk or hear others talk.

**Comment by nearbyplayer** [comment]
I don't see how you moving hosts has anything to do with the script not working. If you have a solution to this issue please by all means put in a PR.
