### ISSUE TITLE
How upgrade esx_voice

### ISSUE THREAD

**Issue by m3ntorsky** [ESX-Org/esx_voice#3]
Hello! Could you tell me how can I update the script to look like the picture?
Small yellow bar( eat ), small blue bar ( water ) white bar (deactive voice) / purple bar (active voice)
![bez_tytuu](https://user-images.githubusercontent.com/28738655/41205357-261da8fc-6cf2-11e8-93ff-2b24700ea6a3.png)

**Comment by nearbyplayer** [comment]
Hi, since this isn't an issue I'm going to close this.
